const productsData = [
    { id: 1, name: 'biotol', description: 'This is product 1 description', image: '/src/assets/Items/Salo.png' },
    { id: 2, name: 'Biotol', description: 'This is product 2 description', image: '/src/assets/Items/Salo(2).png' },
    { id: 4, name: 'Biotol', description: 'This is product 3 description', image: '/src/assets/Items/Salo(3).png' },
    { id: 5, name: 'Biotol', description: 'This is product 3 description', image: '/src/assets/Items/Salo(4).png' },
    { id: 6, name: 'Biotol', description: 'This is product 3 description', image: '/src/assets/Items/Salo(5).png' },
    { id: 8, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(7).png' },
    { id: 9, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(8).png' },
    { id: 10, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(9).png' },
    { id: 11, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(10).png' },
    { id: 12, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(11).png' },
    { id: 13, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(12).png' },
    { id: 14, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(13).png' },
    { id: 15, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(14).png' },
    { id: 16, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(15).png' },
    { id: 17, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(17).png' },
    { id: 18, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(18).png' },
    { id: 19, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(19).png' },
    { id: 20, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(20).png' },
    { id: 21, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(21).png' },
    { id: 22, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(22).png' },
    { id: 23, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(23).png' },
    { id: 24, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(24).png' },
    { id: 25, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(25).png' },
    { id: 26, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(26).png' },
    { id: 27, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(27).png' },
    { id: 28, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(28).png' },
    { id: 29, name: 'Product 3', description: 'This is product 3 description', image: '/src/assets/Items/Salo(29).png' },
];
  
  export default productsData;
  